plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - Engine/index.md
defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "sidebar"